# Generated by Django 5.2.3 on 2025-07-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_first_name_person_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
